<?php

// autoload.php @generated by Composer(altered by Nosto Phing)

require_once dir(__FILE__) . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInitaeb7fe730b852f336baa5f99aedc6502::getLoader();
